#!/bin/bash

## Assing Vars
# workspaceFolder=$1
# program=$1

program=${PWD##*/}

echo -e "\e[1m\e[100m####### ####### ####### ######### ####### ####### #######" ; 
echo "####### ####### ####### Compiling ####### ####### #######" ; 
echo "####### ####### ####### ######### ####### ####### #######" ; 
echo -e "\e[0m"

## Compile Program

### Gives all command
# program_r=$(cmake --build $workspaceFolder/build --config Debug --target all -- -j 2) ;

### Gives a part of the command
#  program_r=( $(cmake --build $workspaceFolder/build --config Debug --target all -- -j 2)) ;

### Does not return the string 
# cmake --build $workspaceFolder/build --config Debug --target all -- -j 2 ;

# time kitty sh -c "$workspaceFolder/SH_files/Cmake_Compile_D $workspaceFolder ";

time cmake --build build/Debug --config Debug --target all -- -j `nproc` ; 
# cmake --build $workspaceFolder/build --config Debug --target all -- -j `nproc` ;

# echo $?;
# if [[ $program_r != 'ninja: no work to do.' ]]; then
# 	echo $program_r;
# 	echo
# 	echo
# 	echo -e "\e[1m\e[100m####### ####### ####### ######### ####### ####### #######" ; 
# 	echo "####### ####### ####### Completed ####### ####### #######" ; 
# 	echo "####### ####### ####### ######### ####### ####### #######" ; 
# 	echo -e "\e[0m"
# else
# 	echo "####### ####### ####### Nothing ####### ####### #######" ; 
# 	exit; 
# 	exec bash;
# fi

echo
echo
echo -e "\e[1m\e[100m####### ####### ####### ######### ####### ####### #######" ; 
echo "####### ####### ####### Compiled ####### ####### #######" ; 
echo "####### ####### ####### ######### ####### ####### #######" ; 
echo -e "\e[0m"

read  -n 1; 

echo
echo

echo "Debug - Run: " $program
echo
echo
./build/Debug/bin/$program

echo
echo

read  -n 2; 
exit; 
exec bash;

