#!/bin/bash

echo -e "\e[1m\e[100m####### ####### ####### ######### ####### ####### #######" ; 
echo "####### ####### ####### Compiling ####### ####### #######" ; 
echo "####### ####### ####### ######### ####### ####### #######" ; 
echo -e "\e[0m"

# cmake --build build/Debug --config Debug --target all -- -j 2 ;
cmake --build build/Debug --config Debug --target all -- -j `nproc` ;
# cmake --build $workspaceFolder/build --config Debug --target all -- -j `nproc` ;

echo
echo
echo -e "\e[1m\e[100m####### ####### ####### ######### ####### ####### #######" ; 
echo "####### ####### ####### Completed ####### ####### #######" ; 
echo "####### ####### ####### ######### ####### ####### #######" ; 
echo -e "\e[0m"


read  -n 1; 
exit; 
exec bash;
