#!/bin/bash

## Assing Vars
workspaceFolder=$1
# program=$2

echo -e "\e[1m--------- --------------------------- ---------"
echo -e "--------- Generate | Terminal | Cmake ---------"
echo -e "--------- --------------------------- ---------";
echo -e "\e[100m \e[1m"
echo -e "WorkSpace Directory: \e[0m"
# echo $1	## Bash/File/Program input
echo $workspaceFolder	## Bash/File/Program input
echo -e "\e[100m \e[1m \e[0m"
echo 

##
### Compile
echo -e "\e[1m\e[100m####### ####### ####### ####### ####### ####### #######" ; 
echo "####### ####### ####### Generate ####### ####### #######" ; 
echo "####### ####### ####### ####### ####### ####### #######" ; 
echo -e "\e[0m"
echo ;

cd $workspaceFolder

### If the build folder does not exist, mkdir
if [ ! -d "build" ]
then
		mkdir -p -v "build"
else
		echo "build find it!"
fi

echo
cd build;
pwd
echo
echo

# ls -al ;

### Unix 
# cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..
# echo
# echo "+++++ Generated using Unix Makefiles +++++"


### Ninja 
cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..

# cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" -DCMAKE_EXPORT_COMPILE_COMMANDS=1..

echo
echo "+++++ Generated using Ninja +++++"

##
###
echo ; 
echo ; 
echo -e "\e[1m***** ***** ******** ****** ***** ***** *****" ; 
echo "***** ***** ***** Generated ***** ***** *****" ; 
echo "***** ***** ***** ********* ***** ***** *****" ; 
echo -e "\e[0m"
read  -n 1; 
exit; 
exec bash;



# echo "Create C++ Cmake Project!"
# echo "Enter root name:"

# read Root_Name	## User Input

# echo "Enter project name:"
# read project_name

# LibsDir="${Root_Name}/${project_name}/Core/src/"
# MainDir="${Root_Name}/${project_name}/main/"
# TestDir="${Root_Name}/${project_name}/test/"
# Assets="${Root_Name}/Assets"

# if [ ! -d $Root_Name ]
# then
#      mkdir -p -v $LibsDir
#      mkdir -p -v $MainDir
#      mkdir -p -v $TestDir
#      mkdir -p -v $Assets
# else
#      echo "Project exists"
# fi